### ISSUE TITLE
Manual GUI new User not working

### ISSUE THREAD

**Issue by tarkal** [ff36/jnoc#55]
Mike Wing: I was just trying to add a member to the Admin group in dastrax and I got this error no matter what email address I plugged into the email field.

![screen shot 2015-08-19 at 09 21 22](https://cloud.githubusercontent.com/assets/7042623/9350776/c88acf0c-4653-11e5-9852-73696b7a974d.png)

**Comment by cantorfan** [comment]
There is no bug on this case, the error is raised because iit is duplicated email address.  I can not reproduce this issue.

**Comment by tarkal** [comment]
Agreed.
